# Generated by Django 3.0.8 on 2020-09-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='user_id',
        ),
    ]
