version: '3'

services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

  web:
    build: .
    command: runserver
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/static/
      - media_volume:/opt/media/
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
