# Generated by Django 3.1.1 on 2020-09-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0002_auto_20200911_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
