# Generated by Django 3.1.1 on 2020-09-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('stock', models.IntegerField(verbose_name='موجودی انبار')),
                ('price', models.IntegerField(verbose_name='قیمت')),
            ],
        ),
    ]
